spring.application.name=weg_skills

server.servlet.context-path=/api

## Temporary
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:weg_skills}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres123}
spring.datasource.driver-class-name=org.postgresql.Driver
##

springdoc.swagger-ui.path=/docs

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
spring.flyway.validate-migration-naming=true
spring.flyway.clean-disabled=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

minio.endpoint=${MINIO_ENDPOINT:http://localhost:9000}
minio.public-endpoint=${MINIO_PUBLIC_ENDPOINT:http://localhost:9000}

minio.access-key=${MINIO_ROOT_USER:minioadmin}
minio.secret-key=${MINIO_ROOT_PASSWORD:minioadmin123}

minio.buckets.public-assets=${MINIO_PUBLIC_BUCKET:course-public-assets}
minio.buckets.private-videos=${MINIO_PRIVATE_BUCKET:course-private-videos}

minio.upload-expiration=15m
minio.playback-expiration=5m

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=1h
security.jwt.issuer=weg-skills-api

cors.config.origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}