CREATE TABLE lesson_progresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    enrollment_id BIGINT NOT NULL,
    lesson_id BIGINT NOT NULL,

    completed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_lesson_progresses
        PRIMARY KEY (id),

    CONSTRAINT uk_lesson_progress_lesson_enrollment
        UNIQUE (lesson_id, enrollment_id),

    CONSTRAINT fk_lesson_progresses_enrollment
        FOREIGN KEY (enrollment_id)
            REFERENCES enrollments (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_lesson_progresses_lesson
        FOREIGN KEY (lesson_id)
            REFERENCES lessons (id)
            ON DELETE CASCADE
);

CREATE INDEX idx_lesson_progresses
    ON lesson_progresses (enrollment_id);