CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    name VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(32) NOT NULL DEFAULT 'STUDENT',

    birthday DATE,
    phone VARCHAR(20),
    city VARCHAR(128),
    state VARCHAR(128),
    country VARCHAR(128),

    image_media_id BIGINT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_users
        PRIMARY KEY (id),

    CONSTRAINT uk_users_email
        UNIQUE (email),

    CONSTRAINT uk_users_image_media
        UNIQUE (image_media_id),

    CONSTRAINT ck_users_role
        CHECK (
            role IN (
                'STUDENT',
                'INSTRUCTOR',
                'ADMIN'
            )
        )
);