CREATE TABLE medias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    bucket VARCHAR(255) NOT NULL,
    object_key VARCHAR(1024) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(255) NOT NULL,

    expected_size BIGINT NOT NULL,
    actual_size BIGINT,

    media_type VARCHAR(32) NOT NULL,
    media_status VARCHAR(32) NOT NULL DEFAULT 'PENDING_UPLOAD',

    user_id BIGINT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_medias
        PRIMARY KEY (id),

    CONSTRAINT uk_medias_object_key
        UNIQUE (object_key),

    CONSTRAINT ck_medias_expected_size
        CHECK (expected_size > 0),

    CONSTRAINT ck_medias_actual_size
        CHECK (
            actual_size IS NULL
            OR actual_size >= 0
        ),

    CONSTRAINT ck_medias_type
        CHECK (
            media_type IN (
                'COURSE_IMAGE',
                'MODULE_IMAGE',
                'LESSON_VIDEO',
                'USER_IMAGE'
            )
        ),

    CONSTRAINT ck_medias_status
        CHECK (
            media_status IN (
                'PENDING_UPLOAD',
                'READY',
                'FAILED',
                'DELETED'
            )
        ),

    CONSTRAINT fk_medias_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
);

ALTER TABLE users
    ADD CONSTRAINT fk_users_image_media
    FOREIGN KEY (image_media_id)
    REFERENCES medias (id)
    ON DELETE SET NULL;