CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    title VARCHAR(128) NOT NULL,
    description TEXT,

    image_media_id BIGINT,
    instructor_id BIGINT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_courses
        PRIMARY KEY (id),

    CONSTRAINT uk_courses_title
        UNIQUE (title),

    CONSTRAINT uk_courses_image_media
        UNIQUE (image_media_id),

    CONSTRAINT fk_courses_image_media
        FOREIGN KEY (image_media_id)
        REFERENCES medias (id)
        ON DELETE SET NULL,

    CONSTRAINT fk_courses_instructor
        FOREIGN KEY (instructor_id)
        REFERENCES users (id)
        ON DELETE RESTRICT
);