CREATE TABLE modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    title VARCHAR(128) NOT NULL,
    description TEXT,

    course_id BIGINT NOT NULL,
    image_media_id BIGINT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_modules
        PRIMARY KEY (id),

    CONSTRAINT uk_module_title_course
        UNIQUE (title, course_id),

    CONSTRAINT uk_modules_image_media
        UNIQUE (image_media_id),

    CONSTRAINT fk_modules_course
        FOREIGN KEY (course_id)
        REFERENCES courses (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_modules_image_media
        FOREIGN KEY (image_media_id)
        REFERENCES medias (id)
        ON DELETE SET NULL
);