CREATE TABLE lessons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    title VARCHAR(128) NOT NULL,
    description TEXT,
    position BIGINT NOT NULL,

    module_id BIGINT NOT NULL,
    video_media_id BIGINT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_lessons
        PRIMARY KEY (id),

    CONSTRAINT uk_lesson_module_title
        UNIQUE (module_id, title),

    CONSTRAINT uk_lesson_module_position
        UNIQUE (module_id, position)
            DEFERRABLE INITIALLY DEFERRED,

    CONSTRAINT uk_lessons_video_media
        UNIQUE (video_media_id),

    CONSTRAINT fk_lessons_module
        FOREIGN KEY (module_id)
        REFERENCES modules (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_lessons_video_media
        FOREIGN KEY (video_media_id)
        REFERENCES medias (id)
        ON DELETE SET NULL
);