CREATE TABLE enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    user_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,

    enrolled_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_enrollments
        PRIMARY KEY (id),

    CONSTRAINT uk_enrollment_user_course
        UNIQUE (user_id, course_id),

    CONSTRAINT fk_enrollments_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_enrollments_course
        FOREIGN KEY (course_id)
        REFERENCES courses (id)
        ON DELETE CASCADE
);