CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    rate INTEGER NOT NULL,

    user_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_reviews
        PRIMARY KEY (id),

    CONSTRAINT uk_review_user_course
        UNIQUE (user_id, course_id),

    CONSTRAINT ck_reviews_rate
        CHECK (rate BETWEEN 0 AND 10),

    CONSTRAINT fk_reviews_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_reviews_course
        FOREIGN KEY (course_id)
        REFERENCES courses (id)
        ON DELETE CASCADE
);